#!/bin/sh
set -eu

version_file="index.html"
tmp_file="${version_file}.tmp"

awk '
  !updated && match($0, /v[0-9]+\.[0-9]+\.[0-9]+/) {
    old = substr($0, RSTART, RLENGTH)
    split(substr(old, 2), parts, ".")
    next_version = "v" parts[1] "." parts[2] "." (parts[3] + 1)
    $0 = substr($0, 1, RSTART - 1) next_version substr($0, RSTART + RLENGTH)
    updated = 1
    printf "Bumped %s: %s -> %s\n", FILENAME, old, next_version > "/dev/stderr"
  }
  { print }
  END {
    if (!updated) {
      print "No version like v0.3.0 found in index.html" > "/dev/stderr"
      exit 1
    }
  }
' "$version_file" > "$tmp_file"

mv "$tmp_file" "$version_file"
git add "$version_file"
